Repository rehlds/.github, pull requests merged in 2024-11, with the labels that each got.

#18 Add labels template with sync
  .github/labels.yml
  .github/workflows/sync_labels.yml
Labels: 🔥 priority: high, 🕹️ on hold

#25 label suggestions
  .github/labels.yml
Labels: Priority: 🔥 high, Type: 🚀 enhancement, Status: 👀 needs review, Difficulty: 🟢 easy

#24 a lot of meta features
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/template-bug.yml
  .github/ISSUE_TEMPLATE/template-feature.yml
  .github/ISSUE_TEMPLATE/template-question.yml.disabled
  .github/ISSUE_TEMPLATE/template-task.yml
  .github/labels.yml
  .github/pull_request_template.md
  .github/workflows/sync-with-gitlab.yml
  LICENSE
  README.md
  SECURITY.md
  profile/README.md
Labels: Difficulty: 🟡 medium, Priority: ⚠️ medium, Type: 🚀 enhancement, Status: 🚧 in progress
